### ISSUE TITLE
Cant get it to work on visual studio 

### ISSUE THREAD

**Issue by JoseETeixeira** [dandistine/olcPGEDearImGui#1]
no matter what I do I cant get it to work with pixel game engine on windows. Several errors show up. Can you send a built example to the repo source or make a full tutorial on the steps?

**Comment by dandistine** [comment]
There is already an example on lines 124-193.  I did notice that the namespace on line 141 should have been `olc::imgui::` and have updated that.  Other than that change, the example provided builds and renders the demo window for me in VS2017.

**Comment by JoseETeixeira** [comment]
![image](https://user-images.githubusercontent.com/9901373/85595055-e0804c00-b61e-11ea-9530-5d617d6c7c31.png)

**imgui_impl_pge.cpp. It doesn't compile. All the files were included. What am I doing wrong?**

`#define OLC_PGEX_DEAR_IMGUI_IMPLEMENTATION
#include "imgui_impl_pge.h"
#include "olcPixelGameEngine.h"
#include "imgui_impl_opengl2.h"
#include "imgui_internal.h"
#include "imstb_rectpack.h"
#include "imstb_textedit.h"
#include "imstb_truetype.h"
#include "imconfig.h"

class Example : public olc::PixelGameEngine
{
	olc::imgui::PGE_ImGUI pge_imgui;
	int gameLayer;

public:
	Example()
	{
		sAppName = "Test Application";
	}

public:
	bool OnUserCreate() override
	{
		//One time initialization of the Dear ImGui library
		ImGui::CreateContext();
		//Create an instance of the Dear ImGui PGE Integration
		pge_imgui = olc::imgui::PGE_ImGUI();

		//The vi2d for pixel size must match the values given in Construct()
		//Otherwise the mouse will not work correctly
		pge_imgui.ImGui_ImplPGE_Init(this);

		//Initialize the OpenGL2 rendering system
		ImGui_ImplOpenGL2_Init();

		//Create a new Layer which will be used for the game
		gameLayer = CreateLayer();
		//The layer is not enabled by default,  so we need to enable it
		EnableLayer(gameLayer, true);

		//Set a custom render function on layer 0.  Since DrawUI is a member of
		//our class, we need to use std::bind
		SetLayerCustomRenderFunction(0, std::bind(&Example::DrawUI, this));

		return true;
	}

	bool OnUserUpdate(float fElapsedTime) override
	{
		//Change the Draw Target to not be Layer 0
		SetDrawTarget((uint8_t)gameLayer);
		//Game Drawing code here

		return true;
	}

	void DrawUI(void) {
		//These 3 lines are mandatory per-frame initialization
		ImGui_ImplOpenGL2_NewFrame();
		pge_imgui.ImGui_ImplPGE_NewFrame();
		ImGui::NewFrame();

		//Create and react to your UI here
		ImGui::ShowDemoWindow();
		//

		//This finishes the Dear ImGui and renders it to the screen
		ImGui::Render();
		ImGui_ImplOpenGL2_RenderDrawData(ImGui::GetDrawData());
	}
};

int main() {
	Example demo;
	if (demo.Construct(640, 360, 2, 2))
		demo.Start();

	return 0;
}`

**Comment by JoseETeixeira** [comment]
Sorry if I'm asking stupid questions. I'm new to visual studio and have been getting the rust of my c++ by doing some fun projects

**Comment by JoseETeixeira** [comment]
Update: It was me being Stupid and replacing the olc definitions instead of overloading them.
`#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

#define OLC_PGEX_DEAR_IMGUI_IMPLEMENTATION
#include "imgui_impl_pge.h"
#include "imgui_impl_opengl2.h"`

Best Regards
