### ISSUE TITLE
Lack of ready example with makefile

### ISSUE THREAD

**Issue by radekrudak** [dandistine/olcPGEDearImGui#2]
I would like to see some "example" folder with all files needed(including makefile) to build example application.
If that's not problem of course.

**Comment by dandistine** [comment]
I don't really have any plans to create an "example application" as invariably someone will come along and ask for another build system I don't use.  The header has a full listing of the files you need to add to your build, and code for a minimal application which shows the Dear ImGui demo window.  There is nothing special in the process that I am aware of other than adding the cpp files to your build and making sure the headers can all be located by the compiler.
