### ISSUE TITLE
Mouse event handling in combination with TransformedView extension

### ISSUE THREAD

**Issue by CrazyDaisyRecords** [dandistine/olcPGEDearImGui#4]
## Issue
If you use the DearImGui extension with the TransformedView extension, mouse click (and drag and drop) events handled by the DearImGui window are also processed by the TransformedView. Which means, if you move a floating UI window, the TransformedView (in the "Background") also moves.

Is there a way of forcing the DearImGui extension to suppress all Events which has been already handled? Or do you know if there is an easy way to achieve such behavior?

**Comment by dandistine** [comment]
You can use `ImGui::GetIO().WantCaptureMouse` to determine whether or not Dear ImGui wants the mouse (ie, did the click occur on a Dear ImGui window) and decide whether or not to cal the `HandlePanAndZoom()` function based on that.

**Comment by shift-left-software** [comment]
Works perfect. Thanks! ;)
